# Generated by Django 4.0.6 on 2022-09-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField()),
            ],
        ),
    ]
