# Generated by Django 4.0.6 on 2022-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('current_address', models.CharField(max_length=200)),
                ('permament_address', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
