# Generated by Django 4.0.6 on 2022-09-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_alter_contact_phone_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Checkout',
        ),
    ]
