# Generated by Django 4.0.6 on 2022-09-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_serie_date_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='change_password',
            new_name='confirm_password',
        ),
    ]
