# Generated by Django 4.0.6 on 2022-09-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_change_password_change_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='confirm_password',
            new_name='new_password',
        ),
    ]
