# Generated by Django 4.0.6 on 2022-10-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_confirm_password_change_new_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Change',
        ),
    ]
